name: chain
on:
  push:
    branches: ["master"]

permissions: 
  contents: write
  actions: write
jobs:
  chain-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Check
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run trigger.yml --ref master
