name: verify-statuses
on:
  pull_request:
    branches: ["master"]

permissions: 
  contents: write
jobs:
  verify-statuses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Check
        run: |
          status=$(gh api /repos/obsrvr/test-merge-commits/commits/${{ github.event.pull_request.head.sha }}/check-runs | jq -r '.check_runs[] | select(.name=="develop-build") | .conclusion')
          if [ $status != "success" ]; then
            echo status is wrong - $status
            exit 1
          fi
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
