name: verify-statuses
on:
  pull_request:
    branches: ["main"]

permissions: 
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: gh pr status
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
