name: verify-statuses
on:
  pull_request:
    branches: ["master"]

permissions: 
  contents: read
jobs:
  verify-statuses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Check
        run: |
          gh api /repos/obsrvr/test-merge-commits/commits/${{ github.event.pull_request.head.sha }}/check-runs | jq '.check_runs[] | select(.name=="develop-build") | .conclusion'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
