name: pull request approved
on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write

jobs:
  rebase:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: rebase
        run: |
          echo ${{ github.event.pull_request.head.sha }}
