name: pull request comment
on:
  issue_comment:
    types: [created]

permissions: 
  contents: write

jobs:
  rebase:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: rebase
        if: contains(github.event.comment.body, '/rebase')
        run: |
          echo I hear you!
