name: pull request comment
on:
  issue_comment:
    types: [created]
  pull_request:
    branches: ["master"]
    types: [opened, reopened]

permissions: write-all

jobs:
  message:
    if: github.event.pull_request
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Write about rebase
        run: |
            {
                echo "# Instructions"
                echo "* To merge this pull request type \`/rebase\`"
            } > instructions.txt
            gh pr comment ${{ github.event.pull_request.number  }} --body "$(cat instructions.txt)"
  rebase:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: rebase
        id: rebase
        if: contains(github.event.comment.body, '/rebase')
        run: |
          set -e
          echo ${{ github.event.issue.number }}
          COMMIT_REF=$(gh pr view ${{ github.event.issue.number }} --json headRefOid -q ".headRefOid")
          git checkout ${COMMIT_REF}
          git checkout master
          git rebase ${COMMIT_REF}
          git push origin master
      - name: failure
        if: failure() || steps.rebase.conclusion == 'failure'
        run: |
          gh pr comment ${{ github.event.issue.number }} --body "Rebase failed"
      - name: Success
        if: success() || steps.rebase.conclusion == 'success'
        run: |
          gh pr comment ${{ github.event.issue.number }} --body "Merged!"



  


