name: pull request comment
on:
  issue_comment:
    types: [created]

permissions: 
  contents: write

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: rebase
        if: contains(github.event.comment.body, '/rebase')
        run: |
          echo ${{ github.event.pull_request.head.sha }}
